server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  absolute_redirect off;

  location / {
    rewrite ^(.+)/$ $1 break;
    try_files $uri.html $uri/index.html $uri $uri/ =404;
  }

  error_page 404 /404.html;
}
