export const companyLogoPaths = {
	"360": "/company-icons/360.svg",
	"4paradigm": "/company-icons/4paradigm.svg",
	"58": "/company-icons/58.svg",
	alibaba: "/company-icons/alibaba.svg",
	autohome: "/company-icons/autohome.svg",
	baidu: "/company-icons/baidu.svg",
	beike: "/company-icons/beike.svg",
	bilibili: "/company-icons/bilibili.svg",
	"boss-zhipin": "/company-icons/boss-zhipin.svg",
	bytedance: "/company-icons/bytedance.svg",
	didi: "/company-icons/didi.svg",
	dewu: "/company-icons/dewu.svg",
	eleme: "/company-icons/eleme.svg",
	"giant-network": "/company-icons/giant-network.svg",
	"hello-group": "/company-icons/hello-group.svg",
	"horizon-robotics": "/company-icons/horizon-robotics.svg",
	iqiyi: "/company-icons/iqiyi.svg",
	ireader: "/company-icons/ireader.svg",
	jd: "/company-icons/jd.svg",
	"kingsoft-office": "/company-icons/kingsoft-office.svg",
	kuaishou: "/company-icons/kuaishou.svg",
	"kunlun-tech": "/company-icons/kunlun-tech.svg",
	"li-auto": "/company-icons/li-auto.svg",
	"lilith-games": "/company-icons/lilith-games.svg",
	meituan: "/company-icons/meituan.svg",
	mihoyo: "/company-icons/mihoyo.svg",
	pdd: "/company-icons/pdd.svg",
	"perfect-world": "/company-icons/perfect-world.svg",
	qianxin: "/company-icons/qianxin.svg",
	qiniu: "/company-icons/qiniu.svg",
	sensetime: "/company-icons/sensetime.svg",
	sohu: "/company-icons/sohu.svg",
	tal: "/company-icons/tal.svg",
	tencent: "/company-icons/tencent.svg",
	"trip-com": "/company-icons/trip-com.svg",
	ucloud: "/company-icons/ucloud.svg",
	weibo: "/company-icons/weibo.svg",
	xiaohongshu: "/company-icons/xiaohongshu.svg",
	xiaomi: "/company-icons/xiaomi.svg",
	ximalaya: "/company-icons/ximalaya.svg",
	yonyou: "/company-icons/yonyou.svg",
	yoozoo: "/company-icons/yoozoo.svg",
	yuewen: "/company-icons/yuewen.svg",
	zhihu: "/company-icons/zhihu.svg",
} as const;

export type CompanyLogoKey = keyof typeof companyLogoPaths;

export type CompanyGuide = {
	name: string;
	href: string;
	logoKey?: CompanyLogoKey;
	area: string;
	city: "beijing" | "shanghai" | "hangzhou";
};

export const companyGuides: readonly CompanyGuide[] = [
	{ name: "京东", href: "/docs/beijing/jd-headquarters-renting-guide", logoKey: "jd", area: "北京 · 亦庄经海路", city: "beijing" },
	{ name: "阿里巴巴", href: "/docs/beijing/alibaba-renting-guide", logoKey: "alibaba", area: "北京 · 崔各庄 / 望京", city: "beijing" },
	{ name: "字节跳动", href: "/docs/beijing/bytedance-renting-guide", logoKey: "bytedance", area: "北京 · 大钟寺 / 知春路", city: "beijing" },
	{ name: "百度", href: "/docs/beijing/baidu-renting-guide", logoKey: "baidu", area: "北京 · 上地 / 西北旺", city: "beijing" },
	{ name: "小米", href: "/docs/beijing/xiaomi-renting-guide", logoKey: "xiaomi", area: "北京 · 安宁庄", city: "beijing" },
	{ name: "快手", href: "/docs/beijing/kuaishou-renting-guide", logoKey: "kuaishou", area: "北京 · 上地西路", city: "beijing" },
	{ name: "美团", href: "/docs/beijing/meituan-renting-guide", logoKey: "meituan", area: "北京 · 望京东", city: "beijing" },
	{ name: "腾讯", href: "/docs/beijing/tencent-renting-guide", logoKey: "tencent", area: "北京 · 中关村软件园", city: "beijing" },
	{ name: "滴滴", href: "/docs/beijing/didi-renting-guide", logoKey: "didi", area: "北京 · 唐家岭 / 东北旺", city: "beijing" },
	{ name: "微博", href: "/docs/beijing/weibo-renting-guide", logoKey: "weibo", area: "北京 · 新源南路", city: "beijing" },
	{ name: "搜狐", href: "/docs/beijing/sohu-renting-guide", logoKey: "sohu", area: "北京 · 中关村", city: "beijing" },
	{ name: "汽车之家", href: "/docs/beijing/autohome-renting-guide", logoKey: "autohome", area: "北京 · 丹棱街", city: "beijing" },
	{ name: "知乎", href: "/docs/beijing/zhihu-renting-guide", logoKey: "zhihu", area: "北京 · 学清路", city: "beijing" },
	{ name: "BOSS直聘", href: "/docs/beijing/boss-zhipin-renting-guide", logoKey: "boss-zhipin", area: "北京 · 太阳宫", city: "beijing" },
	{ name: "58同城", href: "/docs/beijing/58-renting-guide", logoKey: "58", area: "北京 · 酒仙桥北路", city: "beijing" },
	{ name: "陌陌 / Hello Group", href: "/docs/beijing/hello-group-renting-guide", logoKey: "hello-group", area: "北京 · 望京 SOHO", city: "beijing" },
	{ name: "贝壳", href: "/docs/beijing/beike-renting-guide", logoKey: "beike", area: "北京 · 海淀创业路", city: "beijing" },
	{ name: "第四范式", href: "/docs/beijing/4paradigm-renting-guide", logoKey: "4paradigm", area: "北京 · 上地西路", city: "beijing" },
	{ name: "金山办公", href: "/docs/beijing/kingsoft-office-renting-guide", logoKey: "kingsoft-office", area: "北京 · 西二旗", city: "beijing" },
	{ name: "地平线", href: "/docs/beijing/horizon-robotics-renting-guide", logoKey: "horizon-robotics", area: "北京 · 永丰", city: "beijing" },
	{ name: "用友", href: "/docs/beijing/yonyou-renting-guide", logoKey: "yonyou", area: "北京 · 北清路", city: "beijing" },
	{ name: "爱奇艺", href: "/docs/beijing/iqiyi-renting-guide", logoKey: "iqiyi", area: "北京 · 工体北路", city: "beijing" },
	{ name: "360", href: "/docs/beijing/360-renting-guide", logoKey: "360", area: "北京 · 酒仙桥", city: "beijing" },
	{ name: "完美世界", href: "/docs/beijing/perfect-world-renting-guide", logoKey: "perfect-world", area: "北京 · 北苑路", city: "beijing" },
	{ name: "奇安信", href: "/docs/beijing/qianxin-renting-guide", logoKey: "qianxin", area: "北京 · 西直门外", city: "beijing" },
	{ name: "昆仑万维", href: "/docs/beijing/kunlun-tech-renting-guide", logoKey: "kunlun-tech", area: "北京 · 东城", city: "beijing" },
	{ name: "掌阅科技", href: "/docs/beijing/ireader-renting-guide", logoKey: "ireader", area: "北京 · 四惠东", city: "beijing" },
	{ name: "好未来", href: "/docs/beijing/tal-renting-guide", logoKey: "tal", area: "北京 · 昌平七辛中街", city: "beijing" },
	{ name: "理想汽车", href: "/docs/beijing/li-auto-renting-guide", logoKey: "li-auto", area: "北京 · 顺义文良街", city: "beijing" },
	{ name: "阿里巴巴", href: "/docs/shanghai/alibaba-renting-guide", logoKey: "alibaba", area: "上海 · 张江 / 金科路", city: "shanghai" },
	{ name: "七牛云", href: "/docs/shanghai/qiniu-renting-guide", logoKey: "qiniu", area: "上海 · 张江亮秀路", city: "shanghai" },
	{ name: "阅文集团", href: "/docs/shanghai/yuewen-renting-guide", logoKey: "yuewen", area: "上海 · 陆家嘴滨江", city: "shanghai" },
	{ name: "哔哩哔哩", href: "/docs/shanghai/bilibili-renting-guide", logoKey: "bilibili", area: "上海 · 五角场", city: "shanghai" },
	{ name: "得物", href: "/docs/shanghai/dewu-renting-guide", logoKey: "dewu", area: "上海 · 黄兴路", city: "shanghai" },
	{ name: "UCloud 优刻得", href: "/docs/shanghai/ucloud-renting-guide", logoKey: "ucloud", area: "上海 · 隆昌路", city: "shanghai" },
	{ name: "字节跳动", href: "/docs/shanghai/bytedance-renting-guide", logoKey: "bytedance", area: "上海 · 杨浦 / 闵行", city: "shanghai" },
	{ name: "拼多多 / PDD", href: "/docs/shanghai/pdd-renting-guide", logoKey: "pdd", area: "上海 · 娄山关路", city: "shanghai" },
	{ name: "携程", href: "/docs/shanghai/trip-com-renting-guide", logoKey: "trip-com", area: "上海 · 凌空 SOHO", city: "shanghai" },
	{ name: "腾讯", href: "/docs/shanghai/tencent-renting-guide", logoKey: "tencent", area: "上海 · 徐汇滨江", city: "shanghai" },
	{ name: "米哈游", href: "/docs/shanghai/mihoyo-renting-guide", logoKey: "mihoyo", area: "上海 · 漕河泾", city: "shanghai" },
	{ name: "商汤科技", href: "/docs/shanghai/sensetime-renting-guide", logoKey: "sensetime", area: "上海 · 虹梅路", city: "shanghai" },
	{ name: "游族网络", href: "/docs/shanghai/yoozoo-renting-guide", logoKey: "yoozoo", area: "上海 · 宜山路", city: "shanghai" },
	{ name: "小红书", href: "/docs/shanghai/xiaohongshu-renting-guide", logoKey: "xiaohongshu", area: "上海 · 新天地", city: "shanghai" },
	{ name: "喜马拉雅", href: "/docs/shanghai/ximalaya-renting-guide", logoKey: "ximalaya", area: "上海 · 汶水路", city: "shanghai" },
	{ name: "巨人网络", href: "/docs/shanghai/giant-network-renting-guide", logoKey: "giant-network", area: "上海 · 松江新城", city: "shanghai" },
	{ name: "莉莉丝游戏", href: "/docs/shanghai/lilith-games-renting-guide", logoKey: "lilith-games", area: "上海 · 南翔", city: "shanghai" },
	{ name: "饿了么", href: "/docs/shanghai/eleme-renting-guide", logoKey: "eleme", area: "上海 · 普陀", city: "shanghai" },

	{ name: "阿里巴巴", href: "/docs/hangzhou/alibaba-renting-guide", logoKey: "alibaba", area: "杭州 · 未来科技城", city: "hangzhou" },
	{ name: "蚂蚁集团", href: "/docs/hangzhou/ant-group-renting-guide", area: "杭州 · 西溪 / 之江", city: "hangzhou" },
	{ name: "菜鸟", href: "/docs/hangzhou/cainiao-renting-guide", area: "杭州 · 未来科技城", city: "hangzhou" },
	{ name: "钉钉", href: "/docs/hangzhou/dingtalk-renting-guide", area: "杭州 · 未来科技城", city: "hangzhou" },
	{ name: "网易", href: "/docs/hangzhou/netease-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "字节跳动", href: "/docs/hangzhou/bytedance-renting-guide", logoKey: "bytedance", area: "杭州 · 余杭 / 西湖", city: "hangzhou" },
	{ name: "快手", href: "/docs/hangzhou/kuaishou-renting-guide", logoKey: "kuaishou", area: "杭州 · 余杭", city: "hangzhou" },
	{ name: "海康威视", href: "/docs/hangzhou/hikvision-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "大华股份", href: "/docs/hangzhou/dahua-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "新华三", href: "/docs/hangzhou/h3c-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "同花顺", href: "/docs/hangzhou/tonghuashun-renting-guide", area: "杭州 · 余杭五常", city: "hangzhou" },
	{ name: "有赞", href: "/docs/hangzhou/youzan-renting-guide", area: "杭州 · 西湖 / 黄龙", city: "hangzhou" },
	{ name: "微医", href: "/docs/hangzhou/wedoctor-renting-guide", area: "杭州 · 西湖 / 滨江", city: "hangzhou" },
	{ name: "遥望科技", href: "/docs/hangzhou/yaowang-renting-guide", area: "杭州 · 余杭", city: "hangzhou" },
	{ name: "DeepSeek", href: "/docs/hangzhou/deepseek-renting-guide", area: "杭州 · 西湖", city: "hangzhou" },
	{ name: "宇树科技", href: "/docs/hangzhou/unitree-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "OPPO", href: "/docs/hangzhou/oppo-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "vivo", href: "/docs/hangzhou/vivo-renting-guide", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "群核科技", href: "/docs/hangzhou/manycore-renting-guide", area: "杭州 · 西湖", city: "hangzhou" },
	{ name: "游戏科学", href: "/docs/hangzhou/game-science-renting-guide", area: "杭州 · 西湖", city: "hangzhou" },
];

export const companyGuideCount = companyGuides.length;

export const uniqueCompanyCount = new Set(companyGuides.map((company) => company.name)).size;

export const cityCompanyGuideCounts = {
	beijing: companyGuides.filter((company) => company.city === "beijing").length,
	shanghai: companyGuides.filter((company) => company.city === "shanghai").length,
	hangzhou: companyGuides.filter((company) => company.city === "hangzhou").length,
} as const;
