export const companyLogoPaths = {
	"360": "/company-icons/360.svg",
	"37games": "/company-icons/37games.svg",
	"4paradigm": "/company-icons/4paradigm.svg",
	"58": "/company-icons/58.svg",
	alibaba: "/company-icons/alibaba.svg",
	"ant-group": "/company-icons/ant-group.svg",
	autohome: "/company-icons/autohome.svg",
	baidu: "/company-icons/baidu.svg",
	beike: "/company-icons/beike.svg",
	bgi: "/company-icons/bgi.svg",
	bilibili: "/company-icons/bilibili.svg",
	"boss-zhipin": "/company-icons/boss-zhipin.svg",
	byd: "/company-icons/byd.svg",
	bytedance: "/company-icons/bytedance.svg",
	cainiao: "/company-icons/cainiao.svg",
	cmb: "/company-icons/cmb.svg",
	"cvte-seewo": "/company-icons/cvte-seewo.svg",
	dahua: "/company-icons/dahua.svg",
	deepseek: "/company-icons/deepseek.svg",
	dewu: "/company-icons/dewu.svg",
	didi: "/company-icons/didi.svg",
	dingtalk: "/company-icons/dingtalk.svg",
	dji: "/company-icons/dji.svg",
	duoyi: "/company-icons/duoyi.svg",
	ehang: "/company-icons/ehang.svg",
	eleme: "/company-icons/eleme.svg",
	"gac-aion": "/company-icons/gac-aion.svg",
	"gac-group": "/company-icons/gac-group.svg",
	"game-science": "/company-icons/game-science.svg",
	"giant-network": "/company-icons/giant-network.svg",
	h3c: "/company-icons/h3c.svg",
	haid: "/company-icons/haid.svg",
	"hello-group": "/company-icons/hello-group.svg",
	hikvision: "/company-icons/hikvision.svg",
	honor: "/company-icons/honor.svg",
	"horizon-robotics": "/company-icons/horizon-robotics.svg",
	huawei: "/company-icons/huawei.svg",
	insta360: "/company-icons/insta360.svg",
	iqiyi: "/company-icons/iqiyi.svg",
	ireader: "/company-icons/ireader.svg",
	jd: "/company-icons/jd.svg",
	joyy: "/company-icons/joyy.svg",
	kingdee: "/company-icons/kingdee.svg",
	kingmed: "/company-icons/kingmed.svg",
	"kingsoft-office": "/company-icons/kingsoft-office.svg",
	kuaishou: "/company-icons/kuaishou.svg",
	kugou: "/company-icons/kugou.svg",
	"kunlun-tech": "/company-icons/kunlun-tech.svg",
	"li-auto": "/company-icons/li-auto.svg",
	"lilith-games": "/company-icons/lilith-games.svg",
	manycore: "/company-icons/manycore.svg",
	meituan: "/company-icons/meituan.svg",
	mihoyo: "/company-icons/mihoyo.svg",
	mindray: "/company-icons/mindray.svg",
	mobvista: "/company-icons/mobvista.svg",
	netease: "/company-icons/netease.svg",
	"netease-games": "/company-icons/netease-games.svg",
	oppo: "/company-icons/oppo.svg",
	pdd: "/company-icons/pdd.svg",
	"perfect-world": "/company-icons/perfect-world.svg",
	pingan: "/company-icons/pingan.svg",
	"pony-ai": "/company-icons/pony-ai.svg",
	qianxin: "/company-icons/qianxin.svg",
	qiniu: "/company-icons/qiniu.svg",
	robosense: "/company-icons/robosense.svg",
	sangfor: "/company-icons/sangfor.svg",
	sensetime: "/company-icons/sensetime.svg",
	"sf-express": "/company-icons/sf-express.svg",
	shein: "/company-icons/shein.svg",
	skyworth: "/company-icons/skyworth.svg",
	sohu: "/company-icons/sohu.svg",
	sunwoda: "/company-icons/sunwoda.svg",
	tal: "/company-icons/tal.svg",
	tencent: "/company-icons/tencent.svg",
	tonghuashun: "/company-icons/tonghuashun.svg",
	transsion: "/company-icons/transsion.svg",
	"trip-com": "/company-icons/trip-com.svg",
	ubtech: "/company-icons/ubtech.svg",
	ucloud: "/company-icons/ucloud.svg",
	unitree: "/company-icons/unitree.svg",
	vanke: "/company-icons/vanke.svg",
	vipshop: "/company-icons/vipshop.svg",
	vivo: "/company-icons/vivo.svg",
	webank: "/company-icons/webank.svg",
	wedoctor: "/company-icons/wedoctor.svg",
	weibo: "/company-icons/weibo.svg",
	weride: "/company-icons/weride.svg",
	xiaohongshu: "/company-icons/xiaohongshu.svg",
	xiaomi: "/company-icons/xiaomi.svg",
	ximalaya: "/company-icons/ximalaya.svg",
	xpeng: "/company-icons/xpeng.svg",
	yaowang: "/company-icons/yaowang.svg",
	yonyou: "/company-icons/yonyou.svg",
	yoozoo: "/company-icons/yoozoo.svg",
	youzan: "/company-icons/youzan.svg",
	yuewen: "/company-icons/yuewen.svg",
	zhihu: "/company-icons/zhihu.svg",
	zte: "/company-icons/zte.svg",
} as const;

export type CompanyLogoKey = keyof typeof companyLogoPaths;

export type CompanyGuide = {
	name: string;
	href: string;
	logoKey?: CompanyLogoKey;
	area: string;
	city: "beijing" | "shanghai" | "guangzhou" | "hangzhou" | "shenzhen" | "nanjing";
};

export const companyGuides: readonly CompanyGuide[] = [
	{ name: "京东", href: "/docs/beijing/jd-headquarters-renting-guide", logoKey: "jd", area: "北京 · 亦庄经海路", city: "beijing" },
	{ name: "阿里巴巴", href: "/docs/beijing/alibaba-renting-guide", logoKey: "alibaba", area: "北京 · 崔各庄 / 望京", city: "beijing" },
	{ name: "字节跳动", href: "/docs/beijing/bytedance-renting-guide", logoKey: "bytedance", area: "北京 · 大钟寺 / 知春路", city: "beijing" },
	{ name: "百度", href: "/docs/beijing/baidu-renting-guide", logoKey: "baidu", area: "北京 · 上地 / 西北旺", city: "beijing" },
	{ name: "小米", href: "/docs/beijing/xiaomi-renting-guide", logoKey: "xiaomi", area: "北京 · 安宁庄", city: "beijing" },
	{ name: "快手", href: "/docs/beijing/kuaishou-renting-guide", logoKey: "kuaishou", area: "北京 · 上地西路", city: "beijing" },
	{ name: "美团", href: "/docs/beijing/meituan-renting-guide", logoKey: "meituan", area: "北京 · 望京东", city: "beijing" },
	{ name: "腾讯", href: "/docs/beijing/tencent-renting-guide", logoKey: "tencent", area: "北京 · 中关村软件园", city: "beijing" },
	{ name: "滴滴", href: "/docs/beijing/didi-renting-guide", logoKey: "didi", area: "北京 · 唐家岭 / 东北旺", city: "beijing" },
	{ name: "微博", href: "/docs/beijing/weibo-renting-guide", logoKey: "weibo", area: "北京 · 新源南路", city: "beijing" },
	{ name: "搜狐", href: "/docs/beijing/sohu-renting-guide", logoKey: "sohu", area: "北京 · 中关村", city: "beijing" },
	{ name: "汽车之家", href: "/docs/beijing/autohome-renting-guide", logoKey: "autohome", area: "北京 · 丹棱街", city: "beijing" },
	{ name: "知乎", href: "/docs/beijing/zhihu-renting-guide", logoKey: "zhihu", area: "北京 · 学清路", city: "beijing" },
	{ name: "BOSS直聘", href: "/docs/beijing/boss-zhipin-renting-guide", logoKey: "boss-zhipin", area: "北京 · 太阳宫", city: "beijing" },
	{ name: "58同城", href: "/docs/beijing/58-renting-guide", logoKey: "58", area: "北京 · 酒仙桥北路", city: "beijing" },
	{ name: "陌陌 / Hello Group", href: "/docs/beijing/hello-group-renting-guide", logoKey: "hello-group", area: "北京 · 望京 SOHO", city: "beijing" },
	{ name: "贝壳", href: "/docs/beijing/beike-renting-guide", logoKey: "beike", area: "北京 · 海淀创业路", city: "beijing" },
	{ name: "第四范式", href: "/docs/beijing/4paradigm-renting-guide", logoKey: "4paradigm", area: "北京 · 上地西路", city: "beijing" },
	{ name: "金山办公", href: "/docs/beijing/kingsoft-office-renting-guide", logoKey: "kingsoft-office", area: "北京 · 西二旗", city: "beijing" },
	{ name: "地平线", href: "/docs/beijing/horizon-robotics-renting-guide", logoKey: "horizon-robotics", area: "北京 · 永丰", city: "beijing" },
	{ name: "用友", href: "/docs/beijing/yonyou-renting-guide", logoKey: "yonyou", area: "北京 · 北清路", city: "beijing" },
	{ name: "爱奇艺", href: "/docs/beijing/iqiyi-renting-guide", logoKey: "iqiyi", area: "北京 · 工体北路", city: "beijing" },
	{ name: "360", href: "/docs/beijing/360-renting-guide", logoKey: "360", area: "北京 · 酒仙桥", city: "beijing" },
	{ name: "完美世界", href: "/docs/beijing/perfect-world-renting-guide", logoKey: "perfect-world", area: "北京 · 北苑路", city: "beijing" },
	{ name: "奇安信", href: "/docs/beijing/qianxin-renting-guide", logoKey: "qianxin", area: "北京 · 西直门外", city: "beijing" },
	{ name: "昆仑万维", href: "/docs/beijing/kunlun-tech-renting-guide", logoKey: "kunlun-tech", area: "北京 · 东城", city: "beijing" },
	{ name: "掌阅科技", href: "/docs/beijing/ireader-renting-guide", logoKey: "ireader", area: "北京 · 四惠东", city: "beijing" },
	{ name: "好未来", href: "/docs/beijing/tal-renting-guide", logoKey: "tal", area: "北京 · 昌平七辛中街", city: "beijing" },
	{ name: "理想汽车", href: "/docs/beijing/li-auto-renting-guide", logoKey: "li-auto", area: "北京 · 顺义文良街", city: "beijing" },
	{ name: "阿里巴巴", href: "/docs/shanghai/alibaba-renting-guide", logoKey: "alibaba", area: "上海 · 张江 / 金科路", city: "shanghai" },
	{ name: "七牛云", href: "/docs/shanghai/qiniu-renting-guide", logoKey: "qiniu", area: "上海 · 张江亮秀路", city: "shanghai" },
	{ name: "阅文集团", href: "/docs/shanghai/yuewen-renting-guide", logoKey: "yuewen", area: "上海 · 陆家嘴滨江", city: "shanghai" },
	{ name: "哔哩哔哩", href: "/docs/shanghai/bilibili-renting-guide", logoKey: "bilibili", area: "上海 · 五角场", city: "shanghai" },
	{ name: "得物", href: "/docs/shanghai/dewu-renting-guide", logoKey: "dewu", area: "上海 · 黄兴路", city: "shanghai" },
	{ name: "UCloud 优刻得", href: "/docs/shanghai/ucloud-renting-guide", logoKey: "ucloud", area: "上海 · 隆昌路", city: "shanghai" },
	{ name: "字节跳动", href: "/docs/shanghai/bytedance-renting-guide", logoKey: "bytedance", area: "上海 · 杨浦 / 闵行", city: "shanghai" },
	{ name: "拼多多 / PDD", href: "/docs/shanghai/pdd-renting-guide", logoKey: "pdd", area: "上海 · 娄山关路", city: "shanghai" },
	{ name: "携程", href: "/docs/shanghai/trip-com-renting-guide", logoKey: "trip-com", area: "上海 · 凌空 SOHO", city: "shanghai" },
	{ name: "腾讯", href: "/docs/shanghai/tencent-renting-guide", logoKey: "tencent", area: "上海 · 徐汇滨江", city: "shanghai" },
	{ name: "米哈游", href: "/docs/shanghai/mihoyo-renting-guide", logoKey: "mihoyo", area: "上海 · 漕河泾", city: "shanghai" },
	{ name: "商汤科技", href: "/docs/shanghai/sensetime-renting-guide", logoKey: "sensetime", area: "上海 · 虹梅路", city: "shanghai" },
	{ name: "游族网络", href: "/docs/shanghai/yoozoo-renting-guide", logoKey: "yoozoo", area: "上海 · 宜山路", city: "shanghai" },
	{ name: "小红书", href: "/docs/shanghai/xiaohongshu-renting-guide", logoKey: "xiaohongshu", area: "上海 · 新天地", city: "shanghai" },
	{ name: "喜马拉雅", href: "/docs/shanghai/ximalaya-renting-guide", logoKey: "ximalaya", area: "上海 · 汶水路", city: "shanghai" },
	{ name: "巨人网络", href: "/docs/shanghai/giant-network-renting-guide", logoKey: "giant-network", area: "上海 · 松江新城", city: "shanghai" },
	{ name: "莉莉丝游戏", href: "/docs/shanghai/lilith-games-renting-guide", logoKey: "lilith-games", area: "上海 · 南翔", city: "shanghai" },
	{ name: "饿了么", href: "/docs/shanghai/eleme-renting-guide", logoKey: "eleme", area: "上海 · 普陀", city: "shanghai" },

	{ name: "腾讯 / 微信", href: "/docs/guangzhou/tencent-wechat-renting-guide", logoKey: "tencent", area: "广州 · 海珠琶洲 / T.I.T 周边", city: "guangzhou" },
	{ name: "网易游戏", href: "/docs/guangzhou/netease-games-renting-guide", logoKey: "netease-games", area: "广州 · 天河科韵路 / 智慧城", city: "guangzhou" },
	{ name: "唯品会", href: "/docs/guangzhou/vipshop-renting-guide", logoKey: "vipshop", area: "广州 · 荔湾 / 海珠西侧", city: "guangzhou" },
	{ name: "小鹏汽车", href: "/docs/guangzhou/xpeng-renting-guide", logoKey: "xpeng", area: "广州 · 天河 / 黄埔 / 番禺按团队确认", city: "guangzhou" },
	{ name: "广汽埃安", href: "/docs/guangzhou/gac-aion-renting-guide", logoKey: "gac-aion", area: "广州 · 番禺 / 黄埔产业园", city: "guangzhou" },
	{ name: "广汽集团", href: "/docs/guangzhou/gac-group-renting-guide", logoKey: "gac-group", area: "广州 · 珠江新城 / 番禺 / 黄埔按岗位确认", city: "guangzhou" },
	{ name: "文远知行", href: "/docs/guangzhou/weride-renting-guide", logoKey: "weride", area: "广州 · 黄埔 / 生物岛 / 科学城", city: "guangzhou" },
	{ name: "小马智行", href: "/docs/guangzhou/pony-ai-renting-guide", logoKey: "pony-ai", area: "广州 · 南沙 / 黄埔按团队确认", city: "guangzhou" },
	{ name: "亿航智能", href: "/docs/guangzhou/ehang-renting-guide", logoKey: "ehang", area: "广州 · 黄埔科学城 / 广州开发区", city: "guangzhou" },
	{ name: "三七互娱", href: "/docs/guangzhou/37games-renting-guide", logoKey: "37games", area: "广州 · 广州办公点按团队核验", city: "guangzhou" },
	{ name: "多益网络", href: "/docs/guangzhou/duoyi-renting-guide", logoKey: "duoyi", area: "广州 · 黄埔 / 科学城按楼栋复核", city: "guangzhou" },
	{ name: "欢聚集团", href: "/docs/guangzhou/joyy-renting-guide", logoKey: "joyy", area: "广州 · 番禺 / 广州办公点按团队确认", city: "guangzhou" },
	{ name: "酷狗音乐", href: "/docs/guangzhou/kugou-renting-guide", logoKey: "kugou", area: "广州 · 广州办公点按团队确认", city: "guangzhou" },
	{ name: "SHEIN", href: "/docs/guangzhou/shein-renting-guide", logoKey: "shein", area: "广州 · 番禺 / 海珠 / 供应链办公点", city: "guangzhou" },
	{ name: "CVTE / 希沃", href: "/docs/guangzhou/cvte-seewo-renting-guide", logoKey: "cvte-seewo", area: "广州 · 黄埔科学城 / 广州开发区", city: "guangzhou" },
	{ name: "汇量科技", href: "/docs/guangzhou/mobvista-renting-guide", logoKey: "mobvista", area: "广州 · 广州办公点按团队楼栋确认", city: "guangzhou" },
	{ name: "金域医学", href: "/docs/guangzhou/kingmed-renting-guide", logoKey: "kingmed", area: "广州 · 黄埔 / 科学城 / 医疗检验基地", city: "guangzhou" },
	{ name: "海大集团", href: "/docs/guangzhou/haid-renting-guide", logoKey: "haid", area: "广州 · 番禺 / 南村 / 产业总部", city: "guangzhou" },

	{ name: "阿里巴巴", href: "/docs/hangzhou/alibaba-renting-guide", logoKey: "alibaba", area: "杭州 · 未来科技城", city: "hangzhou" },
	{ name: "蚂蚁集团", href: "/docs/hangzhou/ant-group-renting-guide", logoKey: "ant-group", area: "杭州 · 西溪 / 之江", city: "hangzhou" },
	{ name: "菜鸟", href: "/docs/hangzhou/cainiao-renting-guide", logoKey: "cainiao", area: "杭州 · 未来科技城", city: "hangzhou" },
	{ name: "钉钉", href: "/docs/hangzhou/dingtalk-renting-guide", logoKey: "dingtalk", area: "杭州 · 未来科技城", city: "hangzhou" },
	{ name: "网易", href: "/docs/hangzhou/netease-renting-guide", logoKey: "netease", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "字节跳动", href: "/docs/hangzhou/bytedance-renting-guide", logoKey: "bytedance", area: "杭州 · 余杭 / 西湖", city: "hangzhou" },
	{ name: "快手", href: "/docs/hangzhou/kuaishou-renting-guide", logoKey: "kuaishou", area: "杭州 · 余杭", city: "hangzhou" },
	{ name: "海康威视", href: "/docs/hangzhou/hikvision-renting-guide", logoKey: "hikvision", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "大华股份", href: "/docs/hangzhou/dahua-renting-guide", logoKey: "dahua", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "新华三", href: "/docs/hangzhou/h3c-renting-guide", logoKey: "h3c", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "同花顺", href: "/docs/hangzhou/tonghuashun-renting-guide", logoKey: "tonghuashun", area: "杭州 · 余杭五常", city: "hangzhou" },
	{ name: "有赞", href: "/docs/hangzhou/youzan-renting-guide", logoKey: "youzan", area: "杭州 · 西湖 / 黄龙", city: "hangzhou" },
	{ name: "微医", href: "/docs/hangzhou/wedoctor-renting-guide", logoKey: "wedoctor", area: "杭州 · 西湖 / 滨江", city: "hangzhou" },
	{ name: "遥望科技", href: "/docs/hangzhou/yaowang-renting-guide", logoKey: "yaowang", area: "杭州 · 余杭", city: "hangzhou" },
	{ name: "DeepSeek", href: "/docs/hangzhou/deepseek-renting-guide", logoKey: "deepseek", area: "杭州 · 西湖", city: "hangzhou" },
	{ name: "宇树科技", href: "/docs/hangzhou/unitree-renting-guide", logoKey: "unitree", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "OPPO", href: "/docs/hangzhou/oppo-renting-guide", logoKey: "oppo", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "vivo", href: "/docs/hangzhou/vivo-renting-guide", logoKey: "vivo", area: "杭州 · 滨江", city: "hangzhou" },
	{ name: "群核科技", href: "/docs/hangzhou/manycore-renting-guide", logoKey: "manycore", area: "杭州 · 西湖", city: "hangzhou" },
	{ name: "游戏科学", href: "/docs/hangzhou/game-science-renting-guide", logoKey: "game-science", area: "杭州 · 西湖", city: "hangzhou" },

	{ name: "腾讯", href: "/docs/shenzhen/tencent-renting-guide", logoKey: "tencent", area: "深圳 · 南山科技园 / 深圳湾总部基地", city: "shenzhen" },
	{ name: "华为", href: "/docs/shenzhen/huawei-renting-guide", logoKey: "huawei", area: "深圳 · 龙岗坂田 / 华为基地", city: "shenzhen" },
	{ name: "大疆 DJI", href: "/docs/shenzhen/dji-renting-guide", logoKey: "dji", area: "深圳 · 南山西丽 / 大疆天空之城", city: "shenzhen" },
	{ name: "比亚迪 BYD", href: "/docs/shenzhen/byd-renting-guide", logoKey: "byd", area: "深圳 · 坪山 / 比亚迪园区及实际基地", city: "shenzhen" },
	{ name: "中兴通讯 ZTE", href: "/docs/shenzhen/zte-renting-guide", logoKey: "zte", area: "深圳 · 南山科技园 / 科技南路中兴通讯大厦", city: "shenzhen" },
	{ name: "迈瑞医疗", href: "/docs/shenzhen/mindray-renting-guide", logoKey: "mindray", area: "深圳 · 南山高新区 / 科技十二路迈瑞大厦", city: "shenzhen" },
	{ name: "顺丰控股", href: "/docs/shenzhen/sf-express-renting-guide", logoKey: "sf-express", area: "深圳 · 南山科技园 / 总部办公点，宝安福永等物流基地另核", city: "shenzhen" },
	{ name: "金蝶", href: "/docs/shenzhen/kingdee-renting-guide", logoKey: "kingdee", area: "深圳 · 南山科技园 / 金蝶软件园", city: "shenzhen" },
	{ name: "深信服", href: "/docs/shenzhen/sangfor-renting-guide", logoKey: "sangfor", area: "深圳 · 南山西丽 / 仙洞路深信服科技大厦", city: "shenzhen" },
	{ name: "传音控股", href: "/docs/shenzhen/transsion-renting-guide", logoKey: "transsion", area: "深圳 · 南山留仙洞总部基地 / T33 大厦", city: "shenzhen" },
	{ name: "影石 Insta360", href: "/docs/shenzhen/insta360-renting-guide", logoKey: "insta360", area: "深圳 · 前海 / 恒裕前海金融中心", city: "shenzhen" },
	{ name: "优必选 UBTECH", href: "/docs/shenzhen/ubtech-renting-guide", logoKey: "ubtech", area: "深圳 · 南山智园 / 西丽大学城片区", city: "shenzhen" },
	{ name: "速腾聚创 RoboSense", href: "/docs/shenzhen/robosense-renting-guide", logoKey: "robosense", area: "深圳 · 南山桃源 / 留仙大道红花岭工业区", city: "shenzhen" },
	{ name: "荣耀 HONOR", href: "/docs/shenzhen/honor-renting-guide", logoKey: "honor", area: "深圳 · 具体办公点按团队楼栋复核", city: "shenzhen" },
	{ name: "微众银行 WeBank", href: "/docs/shenzhen/webank-renting-guide", logoKey: "webank", area: "深圳 · 深圳湾科技生态园 / 南山沙河西路", city: "shenzhen" },
	{ name: "平安集团", href: "/docs/shenzhen/pingan-renting-guide", logoKey: "pingan", area: "深圳 · 福田 CBD / 平安金融中心", city: "shenzhen" },
	{ name: "招商银行", href: "/docs/shenzhen/cmb-renting-guide", logoKey: "cmb", area: "深圳 · 福田车公庙 / 招商银行大厦", city: "shenzhen" },
	{ name: "华大基因 BGI", href: "/docs/shenzhen/bgi-renting-guide", logoKey: "bgi", area: "深圳 · 盐田 / 华大基因中心", city: "shenzhen" },
	{ name: "欣旺达", href: "/docs/shenzhen/sunwoda-renting-guide", logoKey: "sunwoda", area: "深圳 · 宝安石岩 / 欣旺达总部工业园", city: "shenzhen" },
	{ name: "万科", href: "/docs/shenzhen/vanke-renting-guide", logoKey: "vanke", area: "深圳 · 盐田大梅沙注册总部 / 福田梅林办公点", city: "shenzhen" },
	{ name: "创维 Skyworth", href: "/docs/shenzhen/skyworth-renting-guide", logoKey: "skyworth", area: "深圳 · 南山高新区 / 科技园办公点", city: "shenzhen" },

	{ name: "南京雨花台 / 软件谷南侧", href: "/docs/nanjing/yuhuatai-software-valley-renting-guide", area: "南京 · 软件大道 / 宁双路 / 凤信路", city: "nanjing" },
	{ name: "焦点科技 / 中国制造网", href: "/docs/nanjing/focuschina-renting-guide", area: "南京 · 江北新区丽景路", city: "nanjing" },
	{ name: "满帮 / 运满满", href: "/docs/nanjing/manbang-yunmanman-renting-guide", area: "南京 · 雨花台凤信路", city: "nanjing" },
	{ name: "诚迈科技", href: "/docs/nanjing/archermind-renting-guide", area: "南京 · 雨花台宁双路", city: "nanjing" },
	{ name: "润和软件", href: "/docs/nanjing/hoperun-renting-guide", area: "南京 · 雨花台软件大道", city: "nanjing" },
	{ name: "中兴通讯 ZTE", href: "/docs/nanjing/zte-binjiang-renting-guide", logoKey: "zte", area: "南京 · 江宁滨江牧龙中路", city: "nanjing" },
	{ name: "途牛旅游网", href: "/docs/nanjing/tuniu-renting-guide", area: "南京 · 玄武大道 / 徐庄", city: "nanjing" },
];

export const companyGuideCount = companyGuides.length;

export const uniqueCompanyCount = new Set(companyGuides.map((company) => company.name)).size;

export const cityCompanyGuideCounts = {
	beijing: companyGuides.filter((company) => company.city === "beijing").length,
	shanghai: companyGuides.filter((company) => company.city === "shanghai").length,
	guangzhou: companyGuides.filter((company) => company.city === "guangzhou").length,
	hangzhou: companyGuides.filter((company) => company.city === "hangzhou").length,
	shenzhen: companyGuides.filter((company) => company.city === "shenzhen").length,
	nanjing: companyGuides.filter((company) => company.city === "nanjing").length,
} as const;
